apiVersion: v1
kind: Service
metadata:
  name: ca-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: couchdb0-k8sorg
  ports:
    - port: 7054
      targetPort: 7054
      protocol: TCP