apiVersion: v1
kind: ConfigMap
metadata:
  name: orderer-configmap
data:
  FABRIC_CA_CLIENT_HOME: /var/hyperledger/fabric-ca-client
  ORDERER_GENERAL_ORDERERTYPE: solo
  ORDERER_CFG_PATH: /var/hyperledger/config
  ORDERER_GENERAL_GENESISPROFILE: SoloOrdererProfile
  ORDERER_ABSOLUTEMAXBYTES: 99 MB
  ORDERER_PREFERREDMAXBYTES: 512 MB
  ORDERER_HOME: /var/hyperledger/orderer
  ORDERER_GENERAL_LOGLEVEL: debug
  ORDERER_GENERAL_LEDGERTYPE: file
  ORDERER_GENERAL_GENESISMETHOD: file
  ORDERER_GENERAL_GENESISFILE: /var/hyperledger/orderer/genesis.block
  CONFIGTX_ORDERER_BATCHSIZE_MAXMESSAGECOUNT: "10"
  CONFIGTX_ORDERER_BATCHTIMEOUT: 1s
  ORDERER_GENERAL_MAXWINDOWSIZE: "1000"
  ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0
  ORDERER_GENERAL_LISTENPORT: "7050"
  ORDERER_GENERAL_LOCALMSPID: OrdererMSP
  ORDERER_GENERAL_LOCALMSPDIR: /var/hyperledger/orderer/msp
  ORDERER_GENERAL_TLS_ENABLED: "true"
  ORDERER_GENERAL_TLS_PRIVATEKEY: /var/hyperledger/orderer/tls/server.key
  ORDERER_GENERAL_TLS_CERTIFICATE: /var/hyperledger/orderer/tls/server.crt
  ORDERER_GENERAL_TLS_ROOTCAS: "/var/hyperledger/orderer/tls/ca.crt"
  ORDERER_TLS_CLIENTAUTHREQUIRED: "false"
  ORDERER_TLS_CLIENTROOTCAS_FILES: /var/hyperledger/users/Admin@example.com/tls/ca.crt
  ORDERER_TLS_CLIENTCERT_FILE: /var/hyperledger/users/Admin@example.com/tls/client.crt
  ORDERER_TLS_CLIENTKEY_FILE: /var/hyperledger/users/Admin@example.com/tls/client.key